version: '3'
services:
  postgres:
    image: "postgres:9.6"
    ports:
      - "5433:5432"
    volumes:
      - "./postgres_data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=event-store
      - POSTGRES_USER=repositive
      - POSTGRES_PASSWORD=repositive

  integration_tests:
    command: /bin/sh -c "npm run testIntegration"
    image: node:10
    working_dir: /opt
    environment:
      - PGUSER=repositive
      - PGPASSWORD=repositive
      - PGDATABASE=event-store
      - PGHOST=postgres
    volumes:
      - .:/opt

