version: 2

workflows:
  version: 2
  test_and_release:
    jobs:
      - test_and_make:
          filters:
            branches:
              ignore:
                - production

jobs:
  test_and_make:
    docker:
      - image: circleci/node:8.9
      - image: postgres:9.6
        environment:
          POSTGRES_DB: event-store
          POSTGRES_USER: repositive
          POSTGRES_PASSWORD: repositive
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: sudo npm install -g npm@latest
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: npm run lint
      - run: npm run compile
      - run: npm run test
      - run: npm run doc
      - run:
          name: Integration tests
          command: npm run testIntegration
          environment:
            PGUSER: repositive
            PGPASSWORD: repositive
            PGDATABASE: event-store
            PGHOST: localhost

      - run: echo "$(git rev-parse --short HEAD)" > tag.txt
